nome = str(input("Digite seu nome completo ")).strip()
print("Analisando seu nome ...")
print("Seu nome em maiúsculas é" , nome.upper()) 
print("Seu nome em minúsculas é" , nome.lower())
print("Seu nome ao todo tem" , len(nome) - nome.count(' ') , "letras")
print("Seu primeiro tem" , nome.find(' ') , "letras")
